// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptikerrDB.Models
{
    public partial class kunden
    {
        public int kundenid { get; set; }
        public string anrede { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public decimal telefonnummer { get; set; }
        public string adresse { get; set; }
        public decimal? kosten { get; set; }
        public decimal bestellungsnummer { get; set; }
        public DateOnly datum { get; set; }
    }
}