// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptikerService.Models
{
    public partial class brillen
    {
        public int modellid { get; set; }
        public string name { get; set; }
        public string art { get; set; }
        public decimal preis { get; set; }
        public string glasart { get; set; }
        public decimal? staerke { get; set; }
        public decimal? stueck { get; set; }
    }
}