// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OptikerService.Models
{
    public partial class mitarbeiter_kunden
    {
        public int? id { get; set; }
        public string name { get; set; }
        public string kundenname { get; set; }
        public int? kundenid { get; set; }
    }
}